In [16]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
plt.style.use('ggplot')
pd.set_option('display.max_columns', None)
%matplotlib inline

In [48]:
df=pd.read_csv('Allegations-of-Harassment-or-Bullying.csv',skiprows=5)

In [70]:
df.shape

(57, 10)

In [55]:
df.head()

,course,State,Total Number of Allegations,Sex,Sex/Race/Color/National Origin,Disability,Sexual Orientation,Religion,Number of Schools,Percent of Schools Reporting
0,enrolled in Advanced Placement mathematics,United States,135192.0,55579.0,30913.0,15345.0,22143.0,11212.0,96360.0,99.50083
1,enrolled in Advanced Placement mathematics,Alabama,1434.0,610.0,516.0,89.0,204.0,15.0,1400.0,100.00000
2,enrolled in Advanced Placement mathematics,Alaska,58.0,26.0,17.0,4.0,11.0,0.0,503.0,100.00000
3,enrolled in Advanced Placement mathematics,Arizona,2780.0,1553.0,485.0,216.0,423.0,103.0,1977.0,99.69651
4,enrolled in Advanced Placement mathematics,Arkansas,1222.0,598.0,405.0,102.0,108.0,9.0,1092.0,99.81685

In [65]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53    False
54    False
55    False
56    False
dtype: bool

In [58]:
df.value_counts()

course                                      State                 Total Number of Allegations  Sex      Sex/Race/Color/National Origin  Disability  Sexual Orientation  Religion  Number of Schools  Percent of Schools Reporting
enrolled in Advanced Placement mathematics  Alabama               1434.0                       610.0    516.0                           89.0        204.0               15.0      1400.0             100.000000                      1
                                            Alaska                58.0                         26.0     17.0                            4.0         11.0                0.0       503.0              100.000000                      1
                                            Nevada                1252.0                       527.0    284.0                           180.0       239.0               22.0      658.0              100.000000                      1
                                            New Hampshire         685.0                        311.0    157.0                           60.0        142.0               15.0      483.0              100.000000                      1
                                            New Jersey            5613.0                       1527.0   2013.0                          831.0       985.0               257.0     2577.0             100.000000                      1
                                            New Mexico            1255.0                       942.0    106.0                           93.0        77.0                37.0      880.0              100.000000                      1
                                            New York              10791.0                      5193.0   2843.0                          784.0       1556.0              415.0     4916.0             99.857608                       1
                                            North Carolina        2291.0                       1861.0   165.0                           38.0        218.0               9.0       2618.0             100.000000                      1
                                            North Dakota          227.0                        97.0     80.0                            13.0        27.0                10.0      481.0              100.000000                      1
                                            Ohio                  2782.0                       1138.0   777.0                           316.0       365.0               186.0     3631.0             100.000000                      1
                                            Oklahoma              1295.0                       606.0    407.0                           107.0       160.0               15.0      1815.0             100.000000                      1
                                            Oregon                2612.0                       1208.0   384.0                           484.0       396.0               140.0     1283.0             100.000000                      1
                                            Pennsylvania          4460.0                       1566.0   965.0                           699.0       785.0               445.0     3027.0             100.000000                      1
                                            Rhode Island          2016.0                       297.0    344.0                           361.0       524.0               490.0     308.0              100.000000                      1
                                            South Carolina        988.0                        433.0    330.0                           107.0       106.0               12.0      1236.0             95.631068                       1
                                            South Dakota          268.0                        179.0    35.0                            27.0        24.0                3.0       688.0              100.000000                      1
                                            Tennessee             5703.0                       1177.0   833.0                           255.0       1824.0              1614.0    1818.0             100.000000                      1
                                            Texas                 3931.0                       1722.0   941.0                           336.0       619.0               313.0     8616.0             100.000000                      1
                                            United States         135192.0                     55579.0  30913.0                         15345.0     22143.0             11212.0   96360.0            99.500830                       1
                                            Utah                  2111.0                       1074.0   499.0                           243.0       108.0               187.0     1009.0             94.846383                       1
                                            Vermont               1106.0                       585.0    216.0                           110.0       180.0               15.0      306.0              100.000000                      1
                                            Virginia              1574.0                       721.0    363.0                           185.0       182.0               123.0     1971.0             100.000000                      1
                                            Washington            3041.0                       1393.0   639.0                           359.0       378.0               272.0     2305.0             100.000000                      1
                                            West Virginia         1116.0                       508.0    302.0                           119.0       168.0               19.0      720.0              100.000000                      1
                                            Wisconsin             2996.0                       1440.0   655.0                           356.0       401.0               144.0     2232.0             100.000000                      1
                                            Nebraska              1217.0                       382.0    306.0                           125.0       87.0                317.0     1064.0             100.000000                      1
                                            Montana               954.0                        369.0    389.0                           83.0        93.0                20.0      825.0              100.000000                      1
                                            Missouri              3424.0                       1671.0   939.0                           473.0       308.0               33.0      2372.0             100.000000                      1
                                            Idaho                 1168.0                       227.0    459.0                           71.0        226.0               185.0     720.0              100.000000                      1
                                            Arizona               2780.0                       1553.0   485.0                           216.0       423.0               103.0     1977.0             99.696510                       1
                                            Arkansas              1222.0                       598.0    405.0                           102.0       108.0               9.0       1092.0             99.816850                       1
                                            California            18197.0                      8899.0   3684.0                          2117.0      2167.0              1330.0    10138.0            99.644900                       1
                                            Colorado              1162.0                       710.0    268.0                           61.0        105.0               18.0      1868.0             89.614561                       1
                                            Connecticut           1017.0                       505.0    255.0                           112.0       98.0                47.0      1238.0             100.000000                      1
                                            Delaware              258.0                        102.0    57.0                            47.0        47.0                5.0       235.0              100.000000                      1
                                            District of Columbia  116.0                        69.0     22.0                            5.0         18.0                2.0       221.0              48.868778                       1
                                            Florida               149.0                        36.0     37.0                            29.0        34.0                13.0      3952.0             100.000000                      1
                                            Georgia               1550.0                       792.0    379.0                           150.0       207.0               22.0      2407.0             100.000000                      1
                                            Hawaii                824.0                        277.0    306.0                           103.0       135.0               3.0       290.0              100.000000                      1
                                            Illinois              19687.0                      4961.0   4053.0                          3145.0      4551.0              2977.0    4081.0             99.705954                       1
                                            Mississippi           731.0                        432.0    146.0                           52.0        83.0                18.0      978.0              100.000000                      1
                                            Indiana               2279.0                       1086.0   522.0                           230.0       344.0               97.0      1879.0             100.000000                      1
                                            Iowa                  1310.0                       518.0    280.0                           227.0       260.0               25.0      1365.0             100.000000                      1
                                            Kansas                2046.0                       902.0    302.0                           121.0       669.0               52.0      1356.0             100.000000                      1
                                            Kentucky              885.0                        444.0    202.0                           79.0        151.0               9.0       1407.0             100.000000                      1
                                            Louisiana             448.0                        208.0    135.0                           50.0        53.0                2.0       1367.0             100.000000                      1
                                            Maine                 581.0                        262.0    158.0                           44.0        103.0               14.0      589.0              100.000000                      1
                                            Maryland              514.0                        249.0    108.0                           70.0        76.0                11.0      1434.0             100.000000                      1
                                            Massachusetts         1842.0                       1011.0   402.0                           210.0       161.0               58.0      1873.0             100.000000                      1
                                            Michigan              5081.0                       2078.0   1196.0                          701.0       878.0               228.0     3616.0             99.972345                       1
                                            Minnesota             5881.0                       1952.0   1489.0                          547.0       1039.0              854.0     2170.0             99.815668                       1
                                            Wyoming               264.0                        145.0    58.0                            19.0        40.0                2.0       365.0              100.000000                      1
Name: count, dtype: int64

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   course                          52 non-null     object
 1   State                           56 non-null     object
 2   Total Number of Allegations     52 non-null     float64
 3   Sex                             52 non-null     float64
 4   Sex/Race/Color/National Origin  52 non-null     float64
 5   Disability                      52 non-null     float64
 6   Sexual Orientation              52 non-null     float64
 7   Religion                        52 non-null     float64
 8   Number of Schools               52 non-null     float64
 9   Percent of Schools Reporting    52 non-null     float64
dtypes: float64(8), object(2)
memory usage: 4.6+ KB

In [62]:
df.describe()

,Total Number of Allegations,Sex,Sex/Race/Color/National Origin,Disability,Sexual Orientation,Religion,Number of Schools,Percent of Schools Reporting
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000
mean,5199.692308,2137.653846,1188.961538,590.192308,851.653846,431.230769,3706.153846,98.595605
std,18772.524692,7702.181020,4284.386372,2150.928218,3099.348761,1603.920009,13232.654765,7.230095
min,58.000000,26.000000,17.000000,4.000000,11.000000,0.000000,221.000000,48.868778
25%,869.750000,307.500000,163.250000,67.750000,96.750000,12.750000,720.000000,100.000000
50%,1302.500000,608.000000,353.500000,120.000000,181.000000,29.000000,1383.500000,100.000000
75%,2835.500000,1404.750000,643.000000,341.000000,406.500000,197.250000,2321.750000,100.000000
max,135192.000000,55579.000000,30913.000000,15345.000000,22143.000000,11212.000000,96360.000000,100.000000

## What To Do Now 
 1. Missing Values
 2. Explore the numerical variables
 3. Explore the categorical variables
 4. Finding Relationship Between Features

In [69]:
df.isnull().sum()

course                            5
State                             1
Total Number of Allegations       5
Sex                               5
Sex/Race/Color/National Origin    5
Disability                        5
Sexual Orientation                5
Religion                          5
Number of Schools                 5
Percent of Schools Reporting      5
dtype: int64